services:
  db: # Имя нашего сервиса
    image: postgres:15 # Используем официальный образ PostgreSQL версии 15 (можешь выбрать другую, но 15/16 - хорошие)
    container_name: library-postgres # Даем контейнеру понятное имя
    environment:
      # Эти переменные используются образом postgres для первичной инициализации
      POSTGRES_USER: library_user # Имя пользователя базы данных
      POSTGRES_PASSWORD: libraryLib # Пароль для пользователя
      POSTGRES_DB: library_db # Имя базы данных, которая будет создана автоматически
    ports:
      # Пробрасываем порт 5432 изнутри контейнера на порт 5432 твоего компьютера
      # Формат: "ХОСТ:КОНТЕЙНЕР"
      # Если порт 5432 на твоем компе занят, можешь поменять первую цифру, например "5433:5432"
      # Тогда в настройках приложения тоже нужно будет указать 5433
      - "5433:5432"
    volumes:
      # Это КРАЙНЕ ВАЖНО для сохранения данных между перезапусками контейнера!
      # Мы создаем именованный volume 'postgres_data' и монтируем его в папку, где Postgres хранит данные
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped # Политика перезапуска: перезапускать, если только не остановлен вручную
    # (Опционально, но полезно) Проверка состояния, чтобы убедиться, что БД готова принимать соединения
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

# Определяем именованный volume, который мы использовали выше
volumes:
  postgres_data: